version: "3"

### LOCAL ###

services:
  # server - fast api
  server:
    build:
      context: ./server/
    ports:
      - 5001:5001
    networks:
      - backend
    volumes:
      - server-storage:/data/server-storage
    environment:
      APP_ENV: dev
      APP_DEBUG: idk
      APP_PORT: 5001
      MONGODB_DATABASE: mydb
      MONGODB_HOSTNAME: mongodb://localhost:27017/
      STORAGE_PATH: /data/server-storage
      SECRET: 2c4fc4e6be22853fec33a243a9327e307dc56f0964d2e89e
      ALGORITHM: HS256
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - translator

### LOCAL ###


  # translator - fast api
  translator:
    build:
      context: ./translator/
    ports:
      - 5002:5002
    networks:
      - backend
    deploy:
      restart_policy:
        condition: on-failure
  
  ### LOCAL ###
networks:
  backend:
    driver: bridge
### LOCAL ###

volumes:
  server-storage:
    driver: local
